experiment_name: 2024-04-26-global-performance

ranges_baran:
  dataset:
    - beers
    - flights
    - hospital
    - tax
    - food

config_baran:
  dataset: "1481"
  n_rows: null
  error_fraction: 1
  error_class: "simple_mcar"
  labeling_budget: 20
  synth_tuples: 100
  auto_instance_cache_model: false
  clean_with_user_input: true
  gpdep_threshold: 0.3
  training_time_limit: 600
  llm_name_corrfm: gpt-3.5-turbo
  feature_generators:
    - auto_instance
    - fd
    - llm_correction
    - llm_master
  classification_model: "ABC"
  vicinity_orders:
    - 1
  vicinity_feature_generator: "naive"
  n_best_pdeps: 3
  synth_cleaning_threshold: 0.9
  test_synth_data_direction: "user_data"
  pdep_features:
    - pr
  fd_feature: "norm_gpdep"
  sampling_technique: "greedy"
  detection_mode: "perfect"
  labeling_error_pct: 0


ranges_gpt4:
  dataset:
    - rayyan

config_gpt4:
  dataset: "1481"
  n_rows: null
  error_fraction: 1
  error_class: "simple_mcar"
  labeling_budget: 20
  synth_tuples: 100
  auto_instance_cache_model: false
  clean_with_user_input: true
  gpdep_threshold: 0.3
  training_time_limit: 600
  llm_name_corrfm: gpt-4-turbo
  feature_generators:
    - auto_instance
    - fd
    - llm_correction
    - llm_master
  classification_model: "ABC"
  vicinity_orders:
    - 1
  vicinity_feature_generator: "naive"
  n_best_pdeps: 3
  synth_cleaning_threshold: 0.9
  test_synth_data_direction: "user_data"
  pdep_features:
    - pr
  fd_feature: "norm_gpdep"
  sampling_technique: "greedy"
  detection_mode: "perfect"
  labeling_error_pct: 0


ranges_renuver:
  dataset:
    - bridges
    - cars
    - glass
    - restaurant
  error_fraction:
    - 1
    - 3

config_renuver:
  dataset: "1481"
  n_rows: null
  error_fraction: 1
  error_class: "simple_mcar"
  labeling_budget: 20
  synth_tuples: 100
  auto_instance_cache_model: false
  clean_with_user_input: true
  gpdep_threshold: 0.3
  training_time_limit: 600
  llm_name_corrfm: gpt-3.5-turbo
  feature_generators:
    - auto_instance
    - fd
    - llm_correction
    - llm_master
  classification_model: "ABC"
  vicinity_orders:
    - 1
  vicinity_feature_generator: "naive"
  n_best_pdeps: 3
  synth_cleaning_threshold: 0.9
  test_synth_data_direction: "user_data"
  pdep_features:
    - pr
  fd_feature: "norm_gpdep"
  sampling_technique: "greedy"
  detection_mode: "perfect"
  labeling_error_pct: 0

ranges_openml:
  dataset:
    - "6"
    - "137"
    - "151"
    - "184"
    - "1481"
    - "41027"
    - "43572"

config_openml:
  dataset: "1481"
  n_rows: 1000
  error_fraction: 5
  error_class: "imputer_simple_mcar"
  labeling_budget: 20
  synth_tuples: 100
  auto_instance_cache_model: false
  clean_with_user_input: true
  gpdep_threshold: 0.3
  training_time_limit: 600
  llm_name_corrfm: gpt-3.5-turbo
  feature_generators:
    - auto_instance
    - fd
    - llm_correction
    - llm_master
  classification_model: "ABC"
  vicinity_orders:
    - 1
  vicinity_feature_generator: "naive"
  n_best_pdeps: 3
  synth_cleaning_threshold: 0.9
  test_synth_data_direction: "user_data"
  pdep_features:
    - pr
  fd_feature: "norm_gpdep"
  sampling_technique: "greedy"
  detection_mode: "perfect"
  labeling_error_pct: 0

runs: 3
